name: CI/CD for Spring Boot Hello World

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: cd demo && mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to ACR
        run: |
         docker login --username=LancerBlackLing crpi-kb7j4bn5aam09voc.cn-hangzhou.personal.cr.aliyuncs.com

      - name: Build and Push Docker image
        run: |
          cd demo
          # 构建本地镜像
          docker build -t springboot-hello-world:latest .
    
          # 打标签
          # 将所有变量转换为小写
          REGISTRY_URL=$(echo "${{ secrets.ALIYUN_REGISTRY_URL }}" | tr '[:upper:]' '[:lower:]')
          NAMESPACE=$(echo "${{ secrets.ALIYUN_NAMESPACE }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ secrets.ALIYUN_REPO_NAME }}" | tr '[:upper:]' '[:lower:]')
          
          # 使用转换后的小写变量进行标记和推送
          docker tag springboot-hello-world:latest ${REGISTRY_URL}/${NAMESPACE}/${REPO_NAME}:latest
    
          # 推送镜像
          docker push ${REGISTRY_URL}/${NAMESPACE}/${REPO_NAME}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.ALIYUN_KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          # 将所有变量转换为小写
          REGISTRY_URL=$(echo "${{ secrets.ALIYUN_REGISTRY_URL }}" | tr '[:upper:]' '[:lower:]')
          NAMESPACE=$(echo "${{ secrets.ALIYUN_NAMESPACE }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ secrets.ALIYUN_REPO_NAME }}" | tr '[:upper:]' '[:lower:]')
          
          # 使用转换后的小写变量更新部署
          kubectl set image deployment/springboot-hello-world springboot-hello-world=${REGISTRY_URL}/${NAMESPACE}/${REPO_NAME}:latest

