name: CI/CD for Spring Boot Hello World

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: cd demo && mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to ACR
        run: |
          echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login --username=LancerBlackLing --password-stdin crpi-kb7j4bn5aam09voc.cn-hangzhou.personal.cr.aliyuncs.com

      - name: Build and Push Docker image
        run: |
          cd demo
          # 设置变量并转换为小写
          REGISTRY_URL=$(echo "${{ secrets.ALIYUN_REGISTRY_URL }}" | tr '[:upper:]' '[:lower:]')
          NAMESPACE=$(echo "${{ secrets.ALIYUN_NAMESPACE }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ secrets.ALIYUN_REPO_NAME }}" | tr '[:upper:]' '[:lower:]')

          # 构建本地镜像
          docker build -t springboot-hello-world:latest .
          
          # 获取镜像ID并存储为环境变量
          IMAGE_ID=$(docker images -q springboot-hello-world:latest)
          echo "构建的镜像ID: $IMAGE_ID"
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
    
          # 打标签
          docker tag ${IMAGE_ID} crpi-kb7j4bn5aam09voc.cn-hangzhou.personal.cr.aliyuncs.com/hello_app/springboot-hello-world:latest
    
          # 推送镜像
          docker push crpi-kb7j4bn5aam09voc.cn-hangzhou.personal.cr.aliyuncs.com/hello_app/springboot-hello-world:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.ALIYUN_KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/springboot-hello-world springboot-hello-world=${{ secrets.ALIYUN_REGISTRY_URL }}/${{ secrets.ALIYUN_NAMESPACE }}/${{ secrets.ALIYUN_REPO_NAME }}:latest

